### ISSUE TITLE
DHCP Reservation List Empty

### ISSUE THREAD

**Issue by discreet** [theforeman/foreman_dhcp_browser#15]
When creating DHCP Records through the plugin everything is executed and created successfully however when browsing the subnet there are no DHCP entries listed. The same behavior happens when I provision a new host from Foreman. 
*Note: This was all working prior to upgrading Foreman and the Smart-Proxy (Windows) to 1.8.0.

**Comment by discreet** [comment]
After working with mmoll a bit in IRC we think this might be a proxy issue rather than a dhcp_browser issue.

**Comment by ohadlevy** [comment]
thanks @discreet and @mmoll,tracking at http://projects.theforeman.org/issues/10556
